# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b0d5184956ba3395973c3f1767ffd67"
name = "Harmony-assistant"
handle = "harmony-assistant"
application_url = "https://harmony-assistant.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://harmony-assistant.onrender.com/api/auth" ]

[pos]
embedded = false
